project:
  type: website

website:
  title: "A.J. Lacubtan"
  favicon: images/favicon/favicon-32x32.png
  search: 
    location: navbar
    type: overlay
  navbar:
    logo: images/favicon/apple-touch-icon.svg
    left: 
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
    right:
      - icon: medium
        href: https://medium.com/@ajjhonessaromineslacubtan
      - icon: linkedin
        href: https://www.linkedin.com/in/aj-jhones-lacubtan/
      - icon: github
        href: https://github.com/ajhoneslacubtan
  page-footer: 
    left: "Copyright 2024, AJ Jhones Lacubtan" 
    right: 
      - icon: medium
        href: https://medium.com/@ajjhonessaromineslacubtan
      - icon: linkedin
        href: https://www.linkedin.com/in/aj-jhones-lacubtan/
      - icon: github
        href: https://github.com/ajhoneslacubtan
  cookie-consent:
    type: express
    style: headline
    palette: dark
format:
  html:
    theme:
      light: [flatly, css/light.scss]
      dark: [darkly, css/dark.scss]
    css: css/styles.css
    code-fold: show

editor: visual